---
name: Simple CI
on:

env:
  serveur: $"LT1"

  push:
    branches:
      - main
jobs:
  builds:
    runs-on: unbuntu-lastest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: run a one-line script
        run: echo "hello, world!"
jobs:
  builds:
    runs-on: unbuntu-lastest
    steps:
      - name: run a one-line script
        run: echo $"PERSOMDP"

