---
name: Simple CI
on:
  push:
    branches:
      - main
env:
  serveur: ${{ vars.LT1 }}
  pays: ${{ vars.PAYS }}
  
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: run a one-line script
        run: echo "hello, world!"
      - name: run a one-line script
        run: echo $serveurenv
      - name: run a one-line script
        run: echo $paysenv
      - name: Check_files 
        uses: BorjaOuterelo/test-file-system-action@v0.0.1
        with:
            path: 'BorjaOuterelo/'
            files: 'test-file-system-action'

