---
name: Simple CI
on:
  push:
    branches:
      - main
  
jobs:
  builds:
    runs-on: ubuntu-latest
   
    steps:
            - name: Checkout on current commit
            uses: actions/checkout@v2
            - name: Install PHP dependencies
            uses: lukekortunov/php-composer-install-and-cache@v1
            - name: Run tests
            run:  php vendor/bin/phpunit

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Check domain
    strategy:
      matrix:
        domain:
          - https://m2iformation.fr
          - https://google.fr
    steps:
      - name: Check domain SSL and registry expire date
        id: check-domain
        uses: codex-team/action-check-domain@v1
        with:
          url: ${{ matrix.domain }}

      - name: Create an issue if SSL lifespan days number is below limit 
        if: ${{ steps.check-domain.outputs.ssl-expire-days-left && steps.check-domain.outputs.ssl-expire-days-left < 10 }}
        uses: rishabhgupta/git-action-issue@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 🧨 ${{ matrix.domain }} — SSL cert expires in ${{ steps.check-domain.outputs.ssl-expire-days-left }} days
          body: 'Valid till: `${{ steps.check-domain.outputs.ssl-expire-date }}`'
